### ISSUE TITLE
Will this work in Windows?

### ISSUE THREAD

**Issue by tyeeman** [ivanstojic/pandoc-ssg#1]
I found the GNU Make version for Windows but I'm wondering if that's all that's needed? I see there are 'find' and 'sort' commands within the makefile so are these commands within GNU Make? Sorry I'm not familiar with Linux much. 

If GNU Make is all I need then I guess I will have to rename my executables to remove the .exe extension or leave the .exe extension and modify the Makefile to add the extension?

**Comment by ivanstojic** [comment]
Unfortunately this wasn't designed to work on Windows. It might be possible to make it work, if you had [coreutils](http://gnuwin32.sourceforge.net/packages/coreutils.htm) installed, but no guarantee.
